"""
life_intelligence_lab.calculators.contracts
============================================

Data contracts for the deterministic TVM calculator runtime.

Prototype-only shapes that intentionally mirror -- but do not import from,
and are not identical to -- the CalculationRequest/CalculationResult/
CalculationTrace/AssumptionSet contracts described in PolicyScna's
CLAUDE-LIFE-002/003 design documents.

Field ordering in each dataclass is deliberate and fixed: it is the
ordering used for deterministic canonical serialization (see
`canonical.py`). Do not reorder fields casually.
"""

from __future__ import annotations

import dataclasses
from typing import Dict, List, Optional

RUNTIME_VERSION = "life-intelligence-lab-calc-runtime/0.1.0"

# --- Status vocabularies (closed sets, never free text) --------------------

CALCULATOR_STATUS_ACTIVE = "active"
CALCULATOR_STATUS_RETIRED = "retired"

RESULT_STATUS_SUCCESS = "SUCCESS"
RESULT_STATUS_FAILED_CLOSED = "FAILED_CLOSED"
RESULT_STATUS_INVALID_INPUT = "INVALID_INPUT"
RESULT_STATUS_UNSUPPORTED_CALCULATOR = "UNSUPPORTED_CALCULATOR"
RESULT_STATUS_VALIDATION_FAILED = "VALIDATION_FAILED"

TERMINAL_RESULT_STATUSES = {
    RESULT_STATUS_SUCCESS,
    RESULT_STATUS_FAILED_CLOSED,
    RESULT_STATUS_INVALID_INPUT,
    RESULT_STATUS_UNSUPPORTED_CALCULATOR,
    RESULT_STATUS_VALIDATION_FAILED,
}

# Input-field "kind" vocabulary used by CalculatorDefinition.required_input_schema
FIELD_KIND_MONEY = "money"        # decimal-safe currency amount
FIELD_KIND_DECIMAL = "decimal"    # decimal-safe plain magnitude (no currency)
FIELD_KIND_RATE = "rate"          # decimal-safe rate; MUST carry an explicit unit
FIELD_KIND_COUNT = "count"        # non-negative integer period count
FIELD_KIND_STRING = "string"      # short enumerated/whitelisted string (e.g. currency code)
FIELD_KIND_FLAG = "flag"          # boolean


@dataclasses.dataclass(frozen=True)
class CalculatorDefinition:
    """
    A single registered, versioned calculator. This is the ONLY legitimate
    source of a formula anywhere in the runtime -- nothing else may define
    how a number is computed, and no request-supplied text is ever
    executed as a formula (see ARCHITECTURE.md).
    """

    calculator_id: str
    calculator_version: int
    display_name: str
    formula_id: str
    formula_description: str
    required_input_schema: Dict[str, dict]  # field_name -> {"kind":..., "required":..., ...}
    output_schema: Dict[str, str]           # output_field_name -> "money" | "decimal"
    supported_units: List[str]              # e.g. ["decimal", "percentage"] for rate fields
    supported_methods: List[str]            # e.g. [] or ["deflate_nominal", "exact_real_rate"]
    compounding_convention: str             # e.g. "annual, discrete compounding"
    timing_convention: str                  # e.g. "n/a (single-point valuation)"
    rounding_policy: Dict[str, object]      # e.g. {"money_decimal_places": 2, "mode": "ROUND_HALF_UP"}
    implementation_adapter_id: str          # which formulas.* module implements this
    status: str                             # CALCULATOR_STATUS_ACTIVE | _RETIRED
    requires_currency: bool = False         # if True, CalculationRequest.currency is required and validated
    supersedes: Optional[str] = None        # calculator_id:version this one replaces, if any
    warnings: List[str] = dataclasses.field(default_factory=list)
    limitations: List[str] = dataclasses.field(default_factory=list)

    @property
    def key(self) -> str:
        return f"{self.calculator_id}:v{self.calculator_version}"


@dataclasses.dataclass(frozen=True)
class CalculationRequest:
    """
    A caller's request to run one registered calculator. `request_id` and
    `idempotency_key` are caller-supplied (never generated by the
    runtime) so that nothing in the pipeline introduces a random value
    that would make repeated execution non-reproducible.
    """

    request_id: str
    calculator_id: str
    calculator_version: int
    calculation_date: str  # ISO-8601 date, e.g. "2026-07-26"
    input_values: Dict[str, object]   # raw values as given (str/int only -- see normalization.py)
    input_units: Dict[str, str]       # e.g. {"periodic_rate": "percentage"}
    currency: Optional[str]
    method: Optional[str]             # convention/method selection, where applicable
    source_observation_refs: List[str]
    assumption_refs: List[str]
    requested_rounding: Optional[Dict[str, object]]
    idempotency_key: str


@dataclasses.dataclass(frozen=True)
class NormalizedInput:
    field_name: str
    original_value: str   # string form of exactly what was given
    original_unit: Optional[str]
    normalized_value: str  # decimal-safe canonical string (or "true"/"false" for flags)
    normalized_unit: str   # canonical unit after normalization, e.g. "decimal_fraction"


@dataclasses.dataclass(frozen=True)
class CalculationStep:
    step_number: int
    description: str
    expression: str        # substituted, human-readable expression, e.g. "100000 * (1.08)^10"
    unrounded_value: str    # full-precision Decimal string result of this step


@dataclasses.dataclass(frozen=True)
class CalculationTrace:
    """
    Contains everything required to reproduce the result. Never contains
    executable code -- `expression` fields in steps are display strings,
    not anything eval()'d by any consumer.

    `calculation_date`, `currency`, and `method` are included here even
    though they are not literally listed among the assignment's minimum
    trace fields: `input_hash` is derived from them (see canonical.py),
    so omitting them would silently break the trace's own stated promise
    to "contain everything required to reproduce the result" -- a
    validator could not actually recompute `input_hash` from the trace
    alone without them.
    """

    trace_id: str
    request_id: str
    calculator_id: str
    calculator_version: int
    formula_id: str
    calculation_date: str
    currency: Optional[str]
    method: Optional[str]
    normalized_inputs: List[NormalizedInput]
    steps: List[CalculationStep]
    output_before_rounding: Dict[str, str]
    output_after_rounding: Dict[str, str]
    rounding_applied: Dict[str, object]
    warnings: List[str]
    implementation_adapter_id: str
    implementation_version: str
    dependency_versions: Dict[str, str]
    input_hash: str
    output_hash: str


@dataclasses.dataclass(frozen=True)
class CalculationResult:
    result_id: str
    request_id: str
    calculator_id: str
    calculator_version: int
    status: str  # one of RESULT_STATUS_*
    reason: Optional[str]  # machine-readable reason code, populated for any non-SUCCESS status
    output_values: Optional[Dict[str, str]]   # None unless status == SUCCESS
    output_units: Optional[Dict[str, str]]    # None unless status == SUCCESS
    rounding: Optional[Dict[str, object]]
    warnings: List[str]
    limitations: List[str]
    trace_id: Optional[str]  # None unless status == SUCCESS
    deterministic_input_hash: Optional[str]
    deterministic_output_hash: Optional[str]  # None unless status == SUCCESS


@dataclasses.dataclass(frozen=True)
class CalculationValidationResult:
    validation_id: str
    result_id: str
    trace_id: Optional[str]
    checks: Dict[str, bool]
    overall_status: str  # "valid" | "invalid"
    reasons: List[str]


# --- Fixed field orders for canonical serialization -------------------------

NORMALIZED_INPUT_FIELD_ORDER = ["field_name", "original_value", "original_unit", "normalized_value", "normalized_unit"]
CALCULATION_STEP_FIELD_ORDER = ["step_number", "description", "expression", "unrounded_value"]

CALCULATION_TRACE_FIELD_ORDER = [
    "trace_id", "request_id", "calculator_id", "calculator_version", "formula_id",
    "calculation_date", "currency", "method",
    "normalized_inputs", "steps", "output_before_rounding", "output_after_rounding",
    "rounding_applied", "warnings", "implementation_adapter_id", "implementation_version",
    "dependency_versions", "input_hash", "output_hash",
]

CALCULATION_RESULT_FIELD_ORDER = [
    "result_id", "request_id", "calculator_id", "calculator_version", "status", "reason",
    "output_values", "output_units", "rounding", "warnings", "limitations", "trace_id",
    "deterministic_input_hash", "deterministic_output_hash",
]
